-- COMANDO A EJECUTAR: cat gestion_parroquial_db.sql dummy_data_otros.sql dummy_data_feligres.sql dummy_data_objetos_peticion.sql | mysql

USE gestion_parroquial_db;
INSERT INTO `objetos_de_peticion` (`nombre`) VALUES
('Familia Pérez Rivas'),
('La salud de mi madre'),
('El alma de Luis Alfonso García'),
('20 Años de Matrimonio Rodríguez'),
('Mi abuelo Ricardo'),
('La paz en el mundo'),
('Éxito en la Operación de María'),
('El difunto Carlos Soto'),
('Primer Año de Fallecido Elena Díaz'),
('Mi hija Camila'),
('Por la comunidad de San Antonio'),
('El bienestar de los enfermos'),
('35 Años de la Parroquia'),
('Mi hermano Andrés'),
('El eterno descanso de mi padre'),
('La vocación de servicio'),
('Por los jóvenes sin empleo'),
('El 50 Aniversario de boda de los Valles'),
('Por los viajeros'),
('El alma de Sofía Peña'),
('Mi sobrina Lucía'),
('Salud para el Padre Antonio'),
('Difunta Juana de la Cruz'),
('Por el éxito en los estudios'),
('Mi esposo Jorge'),
('El alma de mi tía Carmen'),
('15 Años de vida de Pedro'),
('La sanación de mi alma'),
('El grupo de catequesis'),
('El difunto Raúl Mendoza'),
('Mi nieta Valentina'),
('Por los misioneros'),
('La salud de mi vecino'),
('El alma de la abuela Clara'),
('25 Años de Matrimonio Fernández'),
('Mi primo David'),
('Por los niños abandonados'),
('El éxito de la empresa'),
('Difunto Hilario Guzmán'),
('Aniversario de Ordenación Sacerdotal'),
('Mi amiga Paula'),
('La fe en la familia'),
('El alma de la hermana Teresa'),
('30 Años de la Coral de la Iglesia'),
('Mi vecino Juan'),
('Por las almas del Purgatorio'),
('Mi cuñado Daniel'),
('Salud y protección para mi hijo'),
('Difunta Margarita Flores'),
('10 Años del Grupo Juvenil'),
('Mi tío Manuel'),
('Por los damnificados'),
('El alma de mi madrina'),
('40 Años de labor de la Hermana María'),
('Mi hermana Patricia'),
('La prosperidad en el país'),
('El alma de Don Ramón'),
('Salud para el Arzobispo'),
('Difunto Pastor Jiménez'),
('Por la conversión de los pecadores'),
('Mi ahijada Estefanía'),
('El alma de la Sra. Petra'),
('5 Años de servicio de la Guardia'),
('Mi prima Ana'),
('La fortaleza en la enfermedad'),
('El alma de mi tío político'),
('22 Años de aniversario de novios'),
('Mi yerno Ricardo'),
('Por los militares'),
('El alma de mi suegra'),
('Aniversario de mi Tío abuelo'),
('Mi nuera Jessica'),
('La unidad de la Iglesia'),
('Difunto Padre Guillermo'),
('Mi bisabuela Elvira'),
('La salud de mi bebé'),
('El alma de la Directora'),
('18 Años de mi sobrino Roberto'),
('Mi tía abuela Josefa'),
('Por la paz familiar'),
('El alma de mi suegro'),
('Salud para el Presidente'),
('Difunto Hermano Santiago'),
('Mi bisabuelo Ciro'),
('La liberación de las adicciones'),
('El alma del Párroco fundador'),
('45 Aniversario de Profesión de Fe'),
('Mi comadre Eliana'),
('Por los artistas'),
('El alma de mi prima lejana'),
('Salud y bienestar para la parroquia'),
('Difunta vecina Consuelo'),
('Mi compadre Fidel'),
('La fe en el mundo'),
('El alma de los niños no nacidos'),
('3 Años de vida de la Tía Luisa'),
('Mi suegro Luis'),
('Por los presos'),
('El alma de mi jefe'),
('Aniversario de mi primera Comunión'),
('Mi suegra Hortensia'),
('La sabiduría para decidir'),
('Difunto Amigo del alma'),
('Mi jefe Gerardo'),
('Por la perseverancia'),
('El alma de mi colega'),
('12 Años de labor de los Voluntarios'),
('Mi colega Fabián'),
('La protección en el viaje'),
('El alma de mi empleado'),
('Salud para los ancianos'),
('Difunta Hermana Clara'),
('Mi empleado Miguel'),
('Por el don de la paciencia'),
('El alma de la patrona'),
('55 Años de vida de mi madre'),
('Mi abuela materna'),
('La fortaleza espiritual'),
('El alma de mi abuelo paterno'),
('Salud para los niños'),
('Difunto Cardenal'),
('Mi abuelo paterno'),
('Por la unidad de los cristianos'),
('El alma de mi tía favorita'),
('28 Años de amor'),
('Mi tío favorito'),
('La guía del Espíritu Santo'),
('El alma de mi prima hermana'),
('Salud para los maestros'),
('Difunta Directora del Colegio'),
('Mi prima hermana'),
('Por el fin de la pandemia'),
('El alma de mi bisabuelo'),
('Aniversario de mi Bautismo'),
('Mi bisabuela'),
('La liberación del miedo'),
('Difunto amigo de infancia'),
('Mi mejor amigo de infancia'),
('Por la protección de los animales'),
('El alma del mendigo de la esquina'),
('1 Año de la Escuela de Música'),
('Mi tía-abuela'),
('La paz en nuestros corazones'),
('El alma del policía caído'),
('Salud para los médicos'),
('Difunta benefactora de la iglesia'),
('Mi primo segundo'),
('Por la libertad de la conciencia'),
('El alma del niño Jesús'),
('4 Años de mi sobrina nieta'),
('Mi sobrino nieta'),
('La curación de los recuerdos'),
('Difunto Padrino de Confirmación'),
('Mi padrino de Confirmación'),
('Por la conversión de los familiares'),
('El alma de mi colega de trabajo'),
('14 Años del grupo de Oración'),
('Mi colega de trabajo'),
('La ayuda a los pobres'),
('El alma del poeta desconocido'),
('Salud para los escritores'),
('Difunta escritora famosa'),
('Mi escritor favorito'),
('Por el don de la humildad'),
('El alma del músico de la iglesia'),
('60 Años de vida de mi padre'),
('Mi padre espiritual'),
('La fe en el futuro'),
('Difunto párroco anterior'),
('Mi músico favorito'),
('El alma del benefactor'),
('33 Aniversario de mi graduación'),
('Mi mentor de vida'),
('Salud y bienestar general'),
('Difunta Madre Superiora'),
('Mi mejor amigo'),
('Por la justicia'),
('El alma de la víctima'),
('9 Años de la fundación'),
('Mi hermano mayor'),
('La protección divina'),
('Difunto Hermano Mayor'),
('Mi hermana menor'),
('Por el respeto'),
('El alma del viajero'),
('Aniversario de mi mascota'),
('Mi vecino de enfrente'),
('La paz en mi país'),
('Difunto amigo de la infancia'),
('Mi ahijado de confirmación'),
('Por la familia'),
('El alma del sacerdote'),
('5 Años de la Casa de Retiro'),
('Mi tía soltera'),
('La fortaleza'),
('Difunto obispo'),
('Mi primo mayor'),
('Por los novios'),
('El alma de mi tatarabuelo'),
('2 Aniversario del Hogar'),
('Mi primo menor'),
('La bendición'),
('Difunta monja amiga'),
('Mi sobrino mayor'),
('Por el trabajo'),
('El alma de mi profesor'),
('1 Año del negocio'),
('Mi sobrino menor'),
('La esperanza'),
('Difunto jardinero de la iglesia'),
('Mi madrina de bautismo'),
('Por los padres'),
('El alma de mi compañero'),
('20 Aniversario del coro'),
('Mi padrino de bautismo'),
('La alegría'),
('Difunta vecina anciana'),
('Mi prima lejana'),
('Por los hijos'),
('El alma de mi excompañero'),
('13 Años de vida del Párroco'),
('Mi excompañero de trabajo'),
('La serenidad'),
('Difunto amigo de la universidad'),
('Mi amigo de la universidad'),
('Por la prosperidad'),
('El alma de la persona que me ayudó'),
('26 Aniversario de nacimiento'),
('Mi benefactora'),
('La salud de mi familia'),
('Difunto colega del trabajo'),
('Mi colega del trabajo'),
('Por la sabiduría'),
('El alma de un buen samaritano'),
('7 Años de vida de mi nieta'),
('Mi buen samaritano'),
('La protección de los niños'),
('Difunto profesor de teología'),
('Mi profesor de teología'),
('Por la unidad'),
('El alma de mi tía abuela'),
('16 Años de matrimonio'),
('Mi tía abuela'),
('La paciencia'),
('Difunto abuelo de un amigo'),
('Mi abuelo de un amigo'),
('Por la humildad'),
('El alma de la vecina'),
('23 Años de sacerdocio'),
('Mi vecina'),
('La bondad'),
('Difunto compañero de clase'),
('Mi compañero de clase'),
('Por la rectitud'),
('El alma del héroe'),
('11 Años de compromiso'),
('Mi héroe personal'),
('La generosidad'),
('Difunta amiga de la escuela'),
('Mi amiga de la escuela'),
('Por la esperanza'),
('El alma del poeta'),
('27 Años de experiencia'),
('Mi poeta favorito'),
('La justicia'),
('Difunto jardinero'),
('Mi jardinero'),
('Por la verdad'),
('El alma del carpintero'),
('19 Años de la Capilla'),
('Mi carpintero'),
('La paz'),
('Difunta costurera'),
('Mi costurera'),
('Por el perdón'),
('El alma del panadero'),
('1 Año de la librería'),
('Mi panadero'),
('La libertad'),
('Difunto bombero'),
('Mi bombero'),
('Por la gratitud'),
('El alma del militar'),
('24 Años de mi hermana'),
('Mi militar favorito'),
('La lealtad'),
('Difunta enfermera'),
('Mi enfermera favorita'),
('Por la salud mental'),
('El alma del doctor'),
('8 Años de la hermandad'),
('Mi doctor favorito'),
('La perseverancia'),
('Difunto deportista'),
('Mi deportista favorito'),
('Por la curación interior'),
('El alma del cantante'),
('17 Años de mi primo'),
('Mi cantante favorito'),
('La inspiración'),
('Difunta maestra de escuela'),
('Mi maestra de escuela'),
('Por el conocimiento'),
('El alma del científico'),
('29 Años de fundación'),
('Mi científico favorito'),
('La inteligencia'),
('Difunto escritor de libros'),
('Mi escritor de libros'),
('Por el crecimiento espiritual'),
('El alma del sacerdote amigo'),
('49 Aniversario del Templo'),
('Mi sacerdote amigo'),
('La sabiduría de Dios'),
('Difunta directora de coro'),
('Mi directora de coro'),
('Por la valentía'),
('El alma del constructor'),
('32 Años de mi nacimiento'),
('Mi constructor favorito'),
('El amor de Dios'),
('Difunto pescador'),
('Mi pescador favorito'),
('Por la bondad del corazón'),
('El alma del campesino'),
('38 Aniversario de vida'),
('Mi campesino favorito'),
('La protección de los animales'),
('Difunto veterinario'),
('Mi veterinario favorito'),
('Por los proyectos futuros'),
('El alma del viajero incansable'),
('42 Años de labor pastoral'),
('Mi viajero incansable'),
('La alegría de vivir'),
('Difunta artista plástica'),
('Mi artista plástica favorita'),
('Por la superación de obstáculos'),
('El alma del músico callejero'),
('47 Años de vida religiosa'),
('Mi músico callejero favorito'),
('La esperanza en tiempos difíciles'),
('Difunta poeta'),
('Mi poeta favorita'),
('Por la protección de los mares'),
('El alma del marino'),
('31 Años de mi primo hermano'),
('Mi primo hermano favorito'),
('La fe inquebrantable'),
('Difunto marino'),
('Mi tierra natal'),
('Por el respeto mutuo'),
('El alma de mi profesor universitario'),
('34 Aniversario de mi hermana'),
('Mi profesor universitario favorito'),
('La honestidad'),
('Difunta bibliotecaria'),
('Mi bibliotecaria favorita'),
('Por la paz interior'),
('El alma del periodista'),
('43 Aniversario de la escuela'),
('Mi periodista favorito'),
('La verdad ante todo'),
('Difunto piloto de avión'),
('Mi piloto de avión favorito'),
('Por los enfermos crónicos'),
('El alma del sacerdote anciano'),
('48 Años de mi padre'),
('Mi sacerdote anciano favorito'),
('La caridad fraterna'),
('Difunta religiosa'),
('Mi comunidad religiosa favorita'),
('Por la unidad familiar'),
('El alma del abuelo ejemplar'),
('39 Aniversario de mi madre'),
('Mi abuelo ejemplar favorito'),
('La fortaleza en la adversidad'),
('Difunta abuela ejemplar')
;